name: contra_square_catalog
description: The webpage for the Contra-Square map and timeline

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  fixnum: ^1.0.1
  fl_chart: ^0.66.0
  flutter_riverpod: ^2.4.5
  google_maps_flutter: ^2.5.0
  http: ^1.1.2
  just_audio: ^0.9.35
  pointer_interceptor: ^0.10.1
  protobuf: ^3.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  protoc_plugin: ^21.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/map_markers/red/
    - assets/map_markers/blue/
